export const EXPERIENCE = [
  {
    company: 'IntoWork',
    role: 'Software Developer',
    period: 'Jul 2025 — Present',
    location: 'Melbourne, Australia',
    logo: '/images/companies/intowork.png',
    achievements: [
      'Collaborated with end users to gather requirements and translate business needs into functional specifications and scalable features.',
      'Built a middleware integration pipeline using Node.js and Next.js to automate third-party lead capture into a CRM.',
      'Led the modernisation of legacy websites into a unified component-based architecture using Next.js, React, TypeScript and Payload CMS, enabling reuse across 18 websites.',
    ],
    stack: [
      'Next.js',
      'Node.js',
      'React',
      'TypeScript',
      'Payload CMS',
      'C#',
      'PHP',
      'WordPress',
      'Docker',
    ],
  },
  {
    company: 'Kargo',
    role: 'Software Engineer',
    period: 'May 2021 — Feb 2025',
    location: 'Waterford, Ireland',
    logo: '/images/companies/kargo.png',
    achievements: [
      'Designed and maintained backend features within a large-scale Ruby on Rails production system.',
      'Built and supported RESTful APIs, background jobs and data-intensive workflows backed by PostgreSQL.',
      'Developed and deployed a scalable video generation platform on AWS capable of producing 24,000 videos within a 24-hour period.',
    ],
    stack: [
      'Ruby',
      'Ruby on Rails',
      'TypeScript',
      'Node.js',
      'React',
      'AWS',
      'Docker',
      'Kubernetes',
      'PostgreSQL',
    ],
  },
  {
    company: 'CGM',
    role: 'Software Engineer',
    period: 'Jun 2019 — May 2021',
    location: 'Waterford, Ireland',
    logo: '/images/companies/cgm.png',
    achievements: [
      'Developed responsive web applications using Angular, C# and .NET while working within Agile development teams.',
      'Contributed to the development and testing of production healthcare software.',
      'Mentored two interns through development tasks, code reviews and day-to-day engineering practices.',
    ],
    stack: ['Angular', 'C#', '.NET', 'MySQL', 'Selenium'],
  },
]